---
# tasks file for tomcat_test
- name: Check response status 
  shell: curl -Is http://127.0.0.1:8080 | head -n 1 | awk '{print $2}'
  register: response

- debug: var=response.stdout

- name: stat /opt/tomcat
  stat: path=/opt/tomcat
  register: st

- debug: msg="Path /opt/tomcat exists and is a directory"
  when: st.stat.isdir is defined and st.stat.isdir

- name: ownership /opt/tomcat
  stat: path=/opt/tomcat
  register: owner

- debug: msg="Ownership /opt/tomcat correct user=tomcat_as, group=tomcat_as_group"
  when: owner.stat.pw_name == 'tomcat_as' and owner.stat.gr_name == 'tomcat_as_group'

- name: Check if tomcat is running
  shell: ps aux | grep tomcat | grep -v grep
  ignore_errors: yes
  changed_when: false
  register: service_tomcat_status

- debug: var=service_tomcat_status.stdout_lines


